### ISSUE TITLE
RabbitMq - Balanced durability mode causes exception.

### ISSUE THREAD

**Issue by kurtwarwick-new** [JasperFx/wolverine#746] opened 2024-02-22 17:01 UTC
**Describe the bug**
If I have Wolverine set up to use RabbitMq with conventional routing, with or without durable in and out boxes, and the durability mode set to Balanced then:

1. This exception is thrown for each listener when starting the application:

```
fail: Wolverine.RabbitMQ.Internal.RabbitMqListener[0]
      Callback error in Rabbit Mq agent Wolverine.RabbitMQ.Internal.RabbitMqListener
      System.InvalidOperationException: Should never be called.
         at RabbitMQ.Client.AsyncDefaultBasicConsumer.RabbitMQ.Client.IBasicConsumer.HandleBasicConsumeOk(String consumerTag)
```

2. This exception is thrown when messages are published to one of the queues:

```
fail: Wolverine.RabbitMQ.Internal.RabbitMqListener[0]
      Callback error in Rabbit Mq agent Wolverine.RabbitMQ.Internal.RabbitMqListener
      System.InvalidOperationException: Should never be called.
         at RabbitMQ.Client.AsyncDefaultBasicConsumer.RabbitMQ.Client.IBasicConsumer.HandleBasicDeliver(String consumerTag, UInt64 deliveryTag, Boolean redelivered, String exchange, String routingKey, IBasicProperties properties, ReadOnlyMemory`1 body)
         at RabbitMQ.Client.Impl.ConcurrentConsumerDispatcher.<>c__DisplayClass10_0.<HandleBasicDeliver>b__0()
```

**To Reproduce**

1. I am using `WolverineFx` and `WolverineFx.RabbitMQ` version 1.18.1 and `RabbitMQ.Client` version 6.8.1
2. I am using the latest docker image for `rabbitmq:management`
3. This is a snippet of code I have used to configure Wolverine with RabbitMq, leaving Wolverine on the default durability mode (Balanced):

```
var configuration = options
  .UseRabbitMq(settings =>
  {
    settings.UserName = "user";
    settings.Password = "password";
    settings.VirtualHost = "virtual_host";
  })
  .UseConventionalRouting(configuration => configuration
    .QueueNameForListener(type => type.FullName.Replace('.', '-').ToLower())
    .ExchangeNameForSending(type => type.FullName.Replace('.', '-').ToLower())
    .ConfigureListeners((listener, context) => listener.UseDurableInbox())
    .ConfigureSending((sender, context) => sender.UseDurableOutbox()))
  .EnableWolverineControlQueues()
  .AutoProvision();
```

4. This is the only configuration I am using for Wolverine:

```
options.AutoBuildMessageStorageOnStartup = true;
options.Policies.AutoApplyTransactions();

options.UseNewtonsoftForSerialization(config =>
{
  config.NullValueHandling = NullValueHandling.Ignore;
  config.TypeNameHandling = TypeNameHandling.None;
  config.Converters.Add(new StringEnumConverter());
  config.ContractResolver = new DefaultContractResolver
  {
    NamingStrategy = new CamelCaseNamingStrategy()
  };
});
```

**Screenshots**

Startup exceptions:

![image](https://github.com/JasperFx/wolverine/assets/61435184/07639fb1-6d59-44ab-8979-83d3f526dca4)

Exceptions when messages are published:

![image](https://github.com/JasperFx/wolverine/assets/61435184/c70ec91d-bde1-446a-a484-a3a0636508db)

**Additional context**
Using the Solo durability mode mitigates these issues, and everything runs as expected.

Thanks

Kurt

**Comment by jeremydmiller** [comment] 2024-03-05 20:48
@kurtwarwick-new Do you think you can do a repro of this? I cannot reproduce this at all locally. I updated to the latest rabbit mq client, switched to using the same Rabbit MQ docker image you were, but cannot make this happen. 

I think what you were seeing had to be related to using the Rabbit MQ control queues, and I did make *some* changes to that I think as part of the Marten 7 / Wolverine 2/ "Critter Stack Pro" projection library work recently. 

I'm closing this in the meantime.

**Closed by jeremydmiller** 2024-03-05 20:48 UTC

**Comment by kurtwarwick-new** [comment] 2024-03-18 14:29
@jeremydmiller - Thanks for getting back to me on this. 

I am glad to inform you that the issue is no longer occuring while using the latest versions of both Marten and Wolverine.

Thanks again.
